---
- name: Validate VLANs config
  ansible.utils.validate:
    data: "{{ lpos_vlans }}"
    criteria:
      - "{{ lookup('file',  '../criteria/lpos_vlans.json') | from_json }}"
    engine: ansible.utils.jsonschema

- name: Validate Switches config
  ansible.utils.validate:
    data: "{{ lpos_switches }}"
    criteria:
      - "{{ lookup('file',  '../criteria/lpos_switches.json') | from_json }}"
    engine: ansible.utils.jsonschema

- name: Validate IpPools config
  ansible.utils.validate:
    data: "{{ lpos_ippools }}"
    criteria:
      - "{{ lookup('file',  '../criteria/lpos_ippools.json') | from_json }}"
    engine: ansible.utils.jsonschema

- name: Validate Tables config
  ansible.utils.validate:
    data: "{{ lpos_tables }}"
    criteria:
      - "{{ lookup('file',  '../criteria/lpos_tables.json') | from_json }}"
    engine: ansible.utils.jsonschema

- name: Validate Devices config
  ansible.utils.validate:
    data: "{{ lpos_devices }}"
    criteria:
      - "{{ lookup('file',  '../criteria/lpos_devices.json') | from_json }}"
    engine: ansible.utils.jsonschema

- name: API login
  nils_ost.lpos.login:
    host: "{{ ansible_host }}"
    port: "{{ lpos_api_port }}"
    path: "{{ lpos_api_path }}"
    user: "admin"
    password: "{{ lpos_admin_pw }}"
  delegate_to: localhost
  register: lpos

- name: Update Settings
  nils_ost.lpos.setting:
    url: "{{ lpos.url }}"
    session_id: "{{ lpos.session_id }}"
    state: update
    key: "{{ setting.key }}"
    value: "{{ setting.value }}"
  delegate_to: localhost

  loop_control:
    loop_var: setting
    label: "{{ setting.key }}"
  with_dict: "{{ lpos_settings }}"

- name: pulling Elements from API
  include_tasks: pulling.yml

- name: purging obsolete Elements
  include_tasks: purging.yml

- name: creating new Elements
  include_tasks: creating.yml
